### ISSUE TITLE
Design the UI for STARRTracker

### ISSUE THREAD

**Issue by Zgell** [UASTARR/starrtracker#1]
This entails creating an interface using QT Designer and producing a `.ui` file that describes the frontend widgets and how they're laid out. This will let us auto-generate a UI class that we can use in the code to handle a lot of the code for instantiating UI elements.

NOTE: Certain elements, such as the map, do not need to be included in the initial interface.

**Comment by Zgell** [comment]
Update (as of Feb 19th at about 11:30am): I got all the tools needed for Qt development set up last night and got a basic Qt program to compile. Will spend some time on the interface very soon so we can move on to #2

**Comment by Zgell** [comment]
I've been working on sorting out some minor issues associated with Qt Creator and getting the setup working. Ran into a problem involving the Qt Creator IDE being full of random bugs (even though code still compiles and runs fine). Finally found the fix today, and it's related to disabling some pre-installed plugins related to Clang. Also ran into an issue where default Qt projects created by Qt Creator crash when closed (side note: lol) but it can be fixed by removing the destructor (since destructor causes double deletion upon closing program). I'll try to make a more formal document shortly about how to set all this up.

**Comment by bpaul2** [comment]
A basic UI for STARRTracker is created, but proper planning for how the UI should look is needed
