### ISSUE TITLE
Implement basic C++ program to create interface

### ISSUE THREAD

**Issue by Zgell** [UASTARR/starrtracker#2]
**Prerequisites**:

- #1 

Once the first iteration of the UI has been designed in Qt Designer, the following should be done in order to get some of the early setup stuff out of the way:

1. Export the `.ui` file as a C++ class from inside Qt Designer. This will compile the UI to a C++ class that will instantiate all of the UI elements in the `.ui` file upon calling the constructor of the class. This file can be called something like `ui.cpp` for now.
2. Create a header called `ui.h` for this file that describes the definition of the class (this is so that it can be imported into other files by the compiler).
3. Create a file called `Application.cpp` (plus a header file called `Application.h`) that contains a basic class that inherits from the UI. No other functionality, other than calling the superclass constructor, is required for now.
4. Create another new file called `main.cpp` and import the "Application" class into this file. In the `int main()` method, instantiate the Application class and get the application running.

This code, when compiled, should open a new window with the interface as described in the `.ui` file. The interface will not have any functionality, but it should appear very similarly to how it did in the Qt Designer editor.

**Comment by bpaul2** [comment]
Closing issue due to completion
