### ISSUE TITLE
Figure out how to integrate a map into a Qt interface

### ISSUE THREAD

**Issue by Zgell** [UASTARR/starrtracker#5]
From the documentation I've seen online, it should definitely be possible to integrate a map component into this program's interface. This is very important because we need a visual component that communicates geospatial information about the location of the rocket as it is being tracked.

Things needed to finish this task:

- Figure out how to integrate a map into a Qt interface
- Figure out if it is possible to do this in Qt Designer
- Figure out how to set the bounds of the map
- Figure out where the data for the map comes from (remember that at competition we don't have access to the internet, so we need to pre-download map data before we come to the site)

_Some potentially useful documentation:_

- [StackOverflow - c++ offline interactive OpenStreetMap in Qt](https://stackoverflow.com/questions/48251004/offline-interactive-openstreetmap-in-qt)

**Comment by Zgell** [comment]
Just wanted to mention that from the cursory reading I've done online, it's possible that we may need to create our own mapping server in order to render content to the UI. I *think* we may be able to avoid this but that is also a way to solve the problem (albeit a complex one).

**Comment by Zgell** [comment]
As of last week this is partially done. We have a way to add a map from OpenStreetMap into the application but we need to figure out how to fetch the data from a local source before we mark this as closed.

**Comment by bpaul2** [comment]
OpenStreetMap API may not be compatible with Ubuntu systems. Requires testing on different Linux systems and on actual ground station. See #15
