### ISSUE TITLE
Write Makefile for project

### ISSUE THREAD

**Issue by Zgell** [UASTARR/starrtracker#6]
The project will need a makefile that can do the following operations:

- Compile the code into a binary
- Clean up any created `*.o` files

This makefile needs to work on Linux, as the target system for StarrTracker is a Linux-based system.

Loosely related to #2 but technically can be done independently of the issue since the file system and structure to be implemented in that issue is clear. For information on how to determine what to compile, read #2 as well as the [project structure documentation found in this GitHub repo's wiki](https://github.com/UASTARR/starrtracker/wiki/Project-Structure).

**Comment by Zgell** [comment]
Update: This is sort of automatically handled by Qt Creator. Qt Creator uses the "QMake" build system, which automatically produces a Makefile to compile the application and link all of the Qt dependencies.

**Comment by Zgell** [comment]
Given that the Qt Creator build system handles this for us, I'll mark this as done. I will note that in the future we can write our own build system if we'd like.

**Comment by bpaul2** [comment]
Closing issue. Will reopen if we're required to create our own Makefile in the future
